In [1]:
import pandas as pd

In [2]:
# Getting the list of kind of business
data = pd.read_csv('data/retail/us_retail_sales.csv', delimiter=',')
data["code_f3d"] = data["naics_code"].astype(str).apply(lambda x: x[:3])
list_kind_of_business = data[["code_f3d", "kind_of_business"]].groupby("code_f3d").agg(set).reset_index(drop=False)
list_kind_of_business

   code_f3d                                   kind_of_business
0       441  {Motor vehicle and parts dealers, New car deal...
1       442  {Furniture stores, All other home furnishings ...
2       443  {Household appliance stores, Electronics store...
3       444  {Paint and wallpaper stores, Hardware stores, ...
4       445  {Food and beverage stores, Beer, wine, and liq...
5       446  {Health and personal care stores, Pharmacies a...
6       447                                {Gasoline stations}
7       448  {Men's clothing stores, Family clothing stores...
8       451  {Sporting goods stores, Sporting goods, hobby,...
9       452  {Department stores(excl. discount department s...
10      453  {Miscellaneous store retailers, Used merchandi...
11      454  {Fuel dealers, Nonstore retailers, Electronic ...
12      722  {Restaurants and other eating places, Drinking...
13      nan  {Retail sales and food services excl gasoline ...